// This file has been dynamically generated by po-compile.
// Do not modify it, all changes will be lost.

public class Messages_pl extends com.greenyetilab.linguaj.Messages {
    public Messages_pl() {
        plainEntries.put("%dx combo!", "%dx combo!");
        plainEntries.put("About", "O grze");
        plainEntries.put("All Stars #%d", "Wszystkie gwiazdki #%d");
        plainEntries.put("Burger Apprentice", "Burgerowy uczeń");
        plainEntries.put("Burger God", "Burgerowy bóg");
        plainEntries.put("Burger Master", "Burgerowy mistrz");
        plainEntries.put("Buy Burger Party goodies!", "Kup gadżety z Burger Party!");
        plainEntries.put("Close Call", "O mały włos");
        plainEntries.put("Code & Design", "Kod i projekt");
        plainEntries.put("Congratulations, you finished level %d-%d!", "Gratulacje, ukończono poziom %d-%d!");
        plainEntries.put("Congratulations, you finished the game!", "Grataluacje, gra została ukończona!");
        plainEntries.put("Congratulations, you finished world %d!", "Gratulacje, ukończono świat %d!");
        plainEntries.put("Creative", "Kreatywnie");
        plainEntries.put("Evening Gamer", "Wieczorny gracz");
        plainEntries.put("Fan", "Fan");
        plainEntries.put("Finish all levels of world %d with 3 stars.", "Ukończ wszystkie poziomy świata %d z 3 gwiazdkami.");
        plainEntries.put("Follow me on Mastodon", "Obserwuj mnie na\nMastodonie");
        plainEntries.put("Fonts", "Czcionki");
        plainEntries.put("Game Over", "Koniec gry");
        plainEntries.put("Get a perfect in all levels of world %d.", "Ukończ perfekcyjnie wszystkie poziomy świata %d.");
        plainEntries.put("Goodies", "Gadżety");
        plainEntries.put("Happy customer!", "Zadowolony klient!");
        plainEntries.put("High score: %d", "Najlepszy wynik: %d");
        plainEntries.put("Level %d-%d", "Poziom %d-%d");
        plainEntries.put("Like the game? Give it a good rate!", "Podoba Ci się ta gra? Daj jej dobrą ocenę!");
        plainEntries.put("Like the game? Support my work!", "Podoba Ci się ta gra? Wesprzyj moją pracę!");
        plainEntries.put("Mastodon", "Mastodon");
        plainEntries.put("Morning Gamer", "Poranny gracz");
        plainEntries.put("Music", "Muzyka");
        plainEntries.put("New High Score!", "Nowy najlepszy wynik!");
        plainEntries.put("New item unlocked!", "Odblokowano nowy przedmiot!");
        plainEntries.put("No high score yet", "Brak najlepszego wyniku");
        plainEntries.put("Paused", "Gra zapauzowana");
        plainEntries.put("Perfect #%d", "Perfekcyjnie #%d");
        plainEntries.put("Practice Area", "Poziom treningowy");
        plainEntries.put("Rate Burger Party", "Oceń Burger Party");
        plainEntries.put("Sound", "Dźwięk");
        plainEntries.put("Sound is OFF", "Dźwięk jest WYŁĄCZONY");
        plainEntries.put("Sound is ON", "Dźwięk jest WŁĄCZONY");
        plainEntries.put("Sounds", "Dźwięki");
        plainEntries.put("Star Collector", "Kolekcjoner gwiazdek");
        plainEntries.put("Support Burger Party", "Wesprzyj Burger Party");
        plainEntries.put("Testers", "Testerzy");
        plainEntries.put("Thank you for playing!", "Dziękuję za grę!");
        plainEntries.put("Thomas Tripon", "Thomas Tripon");
        plainEntries.put("Version %s", "Wersja %s");
        plainEntries.put("Who made this?", "Kto to stworzył?");
        pluralEntries.put(
            new PluralId("+%# sec", "+%# sec"),
            new String[] {
                "+%# sekunda",
                "+%# sekundy",
                "+%# sekund",
            }
        );
        pluralEntries.put(
            new PluralId("1 remaining.", "%# remaining."),
            new String[] {
                "Pozostało: %#.",
                "Pozostało: %#.",
                "Pozostało: %#.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-close-call", "Finish a level with less than %# seconds left."),
            new String[] {
                "Ukończ poziom z jedną sekundą lub mniej na liczniku.",
                "Ukończ poziom z %# sekundami lub mniej na liczniku.",
                "Ukończ poziom z %# sekundami lub mniej na liczniku.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-collect", "Collect %# stars."),
            new String[] {
                "Zbierz jedną gwiazdkę",
                "Zbierz %# gwiazdki",
                "Zbierz %# gwiazdek",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-creative", "Create %# different burgers in the practice area."),
            new String[] {
                "Stwórz jednego burgera w poziomie treningowym.",
                "Stwórz %# różne burgery w poziomie treningowym.",
                "Stwórz %# różnych burgerów w poziomie treningowym.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-evening", "Start a game between 7PM and 11PM for %# days."),
            new String[] {
                "Uruchom grę jeden raz pomiędzy 19:00 i 23:00.",
                "Uruchom grę pomiędzy 19:00 i 23:00 przez %# dni.",
                "Uruchom grę pomiędzy 19:00 i 23:00 przez %# dni.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-fan", "Play %# levels."),
            new String[] {
                "Zagraj w jeden poziom.",
                "Zagraf w %# poziomy.",
                "Zagraj w %# poziomów.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-morning", "Start a game between 7AM and 10AM for %# days."),
            new String[] {
                "Uruchom grę jeden raz pomiędzy 7:00 i 10:00.",
                "Uruchom grę pomiędzy 7:00 i 10:00 przez %# dni.",
                "Uruchom grę pomiędzy 7:00 i 10:00 przez %# dni.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-n-burgers", "Serve %# burgers."),
            new String[] {
                "Podaj jednego burgera.",
                "Podaj %# burgery.",
                "Podaj %# burgerów.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-practice", "Play %# levels to unlock the practice area."),
            new String[] {
                "Zagraj jeden poziom, aby odblokować poziom treningowy.",
                "Zagraj w %# poziomy, aby odblokować poziom treningowy.",
                "Zagraj w %# poziomów, aby odblokować poziom treningowy.",
            }
        );
    }

    @Override
    public int plural(int n) {
        return n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;
    }
}