// This file has been dynamically generated by po-compile.
// Do not modify it, all changes will be lost.

public class Messages_hu extends com.greenyetilab.linguaj.Messages {
    public Messages_hu() {
        plainEntries.put("%dx combo!", "%dx kombó!");
        plainEntries.put("About", "Névjegy");
        plainEntries.put("All Stars #%d", "Összes csillag #%d");
        plainEntries.put("Burger Apprentice", "Burger tanonc");
        plainEntries.put("Burger God", "Burger isten");
        plainEntries.put("Burger Master", "Burger mester");
        plainEntries.put("Buy Burger Party goodies!", "Vásárolj Burger Party\nfinomságokat!");
        plainEntries.put("Close Call", "Közelharc");
        plainEntries.put("Code & Design", "Kódolás és tervezés");
        plainEntries.put("Congratulations, you finished level %d-%d!", "Gratulálunk, befejezted a(z) %d-%d. szintet!");
        plainEntries.put("Congratulations, you finished the game!", "Gratulálunk, befejezted a játékot!");
        plainEntries.put("Congratulations, you finished world %d!", "Gratulálunk, befejezted a(z) %d. világot!");
        plainEntries.put("Creative", "Kreatív");
        plainEntries.put("Evening Gamer", "Éjjeli játékos");
        plainEntries.put("Fan", "Rajongó");
        plainEntries.put("Finish all levels of world %d with 3 stars.", "Fejezd be a(z) %d. világ összes szintjét 3 csillaggal.");
        plainEntries.put("Follow me on Mastodon", "Kövess Mastodonon");
        plainEntries.put("Fonts", "Betűkészletek");
        plainEntries.put("Game Over", "Vége a játéknak");
        plainEntries.put("Get a perfect in all levels of world %d.", "Legyél tökéletes a(z) %d. világ összes szintjén.");
        plainEntries.put("Goodies", "Finomságok");
        plainEntries.put("Happy customer!", "Boldog vásárló!");
        plainEntries.put("High score: %d", "Legmagasabb pontszám: %d");
        plainEntries.put("Level %d-%d", "%d-%d. szint");
        plainEntries.put("Like the game? Give it a good rate!", "Tetszik a játék? Adj rá jó értékelést!");
        plainEntries.put("Like the game? Support my work!", "Tetszik a játék? Támogasd a munkámat!");
        plainEntries.put("Mastodon", "Mastodon");
        plainEntries.put("Morning Gamer", "Reggeli játékos");
        plainEntries.put("Music", "Zene");
        plainEntries.put("New High Score!", "Új legmagasabb pontszám!");
        plainEntries.put("New item unlocked!", "Új elem feloldva!");
        plainEntries.put("No high score yet", "Még nincs legmagasabb pontszám");
        plainEntries.put("Paused", "Szüneteltetve");
        plainEntries.put("Perfect #%d", "Tökéletes #%d");
        plainEntries.put("Practice Area", "Gyakorló terület");
        plainEntries.put("Rate Burger Party", "A Burger Party értékelése");
        plainEntries.put("Sound", "Hang");
        plainEntries.put("Sound is OFF", "Hang kikapcsolva");
        plainEntries.put("Sound is ON", "Hang bekapcsolva");
        plainEntries.put("Sounds", "Hangok");
        plainEntries.put("Star Collector", "Csillaggyűjtő");
        plainEntries.put("Support Burger Party", "A Burger Party támogatása");
        plainEntries.put("Testers", "Tesztelők");
        plainEntries.put("Thank you for playing!", "Köszönjük, hogy játszottál!");
        plainEntries.put("Thomas Tripon", "Thomas Tripon");
        plainEntries.put("Version %s", "Verzió: %s");
        plainEntries.put("Who made this?", "Ki csinálta ezt?");
        pluralEntries.put(
            new PluralId("+%# sec", "+%# sec"),
            new String[] {
                "+%# mp",
                "+%# mp",
            }
        );
        pluralEntries.put(
            new PluralId("1 remaining.", "%# remaining."),
            new String[] {
                "1 van hátra.",
                "%# van hátra.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-close-call", "Finish a level with less than %# seconds left."),
            new String[] {
                "ignore-close-call",
                "Fejezz be egy szintet kevesebb mint %# másodperc alatt.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-collect", "Collect %# stars."),
            new String[] {
                "ignore-collect",
                "Gyűjts %# csillagot.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-creative", "Create %# different burgers in the practice area."),
            new String[] {
                "ignore-creative",
                "Készíts %# különböző burgert a gyakorló területen.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-evening", "Start a game between 7PM and 11PM for %# days."),
            new String[] {
                "ignore-evening",
                "Indíts egy játékot 19 és 23 óra között %# napon át.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-fan", "Play %# levels."),
            new String[] {
                "ignore-fan",
                "Játssz %# szintet.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-morning", "Start a game between 7AM and 10AM for %# days."),
            new String[] {
                "ignore-morning",
                "Indíts egy játékot 7 és 10 óra között %# napon át.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-n-burgers", "Serve %# burgers."),
            new String[] {
                "ignore-n-burgers",
                "Szolgálj fel %# burgert.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-practice", "Play %# levels to unlock the practice area."),
            new String[] {
                "ignore-practice",
                "Játssz %# szintet a gyakorló terület feloldásához.",
            }
        );
    }

    @Override
    public int plural(int n) {
        return (n != 1) ? 1 : 0;
    }
}