// This file has been dynamically generated by po-compile.
// Do not modify it, all changes will be lost.

public class Messages_nl extends com.greenyetilab.linguaj.Messages {
    public Messages_nl() {
        plainEntries.put("%dx combo!", "%dx-combinatie!");
        plainEntries.put("About", "Over");
        plainEntries.put("All Stars #%d", "Sterrenchef #%d");
        plainEntries.put("Burger Apprentice", "Aspirant-burger");
        plainEntries.put("Burger God", "Burgergoeroe");
        plainEntries.put("Burger Master", "Burge(r)meester");
        plainEntries.put("Buy Burger Party goodies!", "Koop Burger Party-fanitems!");
        plainEntries.put("Close Call", "Ken net");
        plainEntries.put("Code & Design", "Code en ontwerp");
        plainEntries.put("Congratulations, you finished level %d-%d!", "Gefeliciteerd! Je hebt level %d-%d afgerond!");
        plainEntries.put("Congratulations, you finished the game!", "Gefeliciteerd! Je hebt het hele spel afgerond!");
        plainEntries.put("Congratulations, you finished world %d!", "Gefeliciteerd! Je hebt wereld %d afgerond!");
        plainEntries.put("Creative", "Creatief met burgers");
        plainEntries.put("Evening Gamer", "Avondmens");
        plainEntries.put("Fan", "Fan");
        plainEntries.put("Finish all levels of world %d with 3 stars.", "Rond alle levels van wereld %d af met 3 sterren.");
        plainEntries.put("Follow me on Mastodon", "Volg me op Mastodon");
        plainEntries.put("Fonts", "Lettertypen");
        plainEntries.put("Game Over", "Spel afgelopen");
        plainEntries.put("Get a perfect in all levels of world %d.", "Rond alle levels van wereld %d af met een perfecte score.");
        plainEntries.put("Goodies", "Fanitems");
        plainEntries.put("Happy customer!", "Tevreden klant!");
        plainEntries.put("High score: %d", "Topscore: %d");
        plainEntries.put("Level %d-%d", "Level %d-%d");
        plainEntries.put("Like the game? Give it a good rate!", "Speel je graag? Laat dan een goede beoordeling achter!");
        plainEntries.put("Like the game? Support my work!", "Speel je graag? Ondersteun dan mijn werk!");
        plainEntries.put("Mastodon", "Mastodon");
        plainEntries.put("Morning Gamer", "Ochtendmens");
        plainEntries.put("Music", "Muziek");
        plainEntries.put("New High Score!", "Nieuwe topscore!");
        plainEntries.put("New item unlocked!", "Nieuw item ontgrendeld!");
        plainEntries.put("No high score yet", "Er zijn nog geen topscores genoteerd");
        plainEntries.put("Paused", "Onderbroken");
        plainEntries.put("Perfect #%d", "#%d is scheepsrecht");
        plainEntries.put("Practice Area", "Oefenterrein");
        plainEntries.put("Rate Burger Party", "Beoordeel Burger Party");
        plainEntries.put("Sound", "Geluid");
        plainEntries.put("Sound is OFF", "Geluid is UIT");
        plainEntries.put("Sound is ON", "Geluid is AAN");
        plainEntries.put("Sounds", "Geluiden");
        plainEntries.put("Star Collector", "Sterrenjager");
        plainEntries.put("Support Burger Party", "Ondersteun Burger Party");
        plainEntries.put("Testers", "Testers");
        plainEntries.put("Thank you for playing!", "Bedankt voor het spelen!");
        plainEntries.put("Thomas Tripon", "Thomas Tripon");
        plainEntries.put("Version %s", "Versie %s");
        plainEntries.put("Who made this?", "Wie heeft dit spel gemaakt?");
        pluralEntries.put(
            new PluralId("+%# sec", "+%# sec"),
            new String[] {
                "+%# sec.",
                "+%# sec.",
            }
        );
        pluralEntries.put(
            new PluralId("1 remaining.", "%# remaining."),
            new String[] {
                "Nog 1 te gaan.",
                "Nog %# te gaan.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-close-call", "Finish a level with less than %# seconds left."),
            new String[] {
                "-",
                "Rond een level af met minder dan %# seconden op de klok.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-collect", "Collect %# stars."),
            new String[] {
                "-",
                "Verzamel %# sterren.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-creative", "Create %# different burgers in the practice area."),
            new String[] {
                "-",
                "Maak %# verschillende burgers op het oefenterrein.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-evening", "Start a game between 7PM and 11PM for %# days."),
            new String[] {
                "-",
                "Speel %# dagen lang tussen 19:00 en 23:00.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-fan", "Play %# levels."),
            new String[] {
                "-",
                "Win %# levels.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-morning", "Start a game between 7AM and 10AM for %# days."),
            new String[] {
                "-",
                "Speel %# dagen lang tussen 7:00 en 10:00.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-n-burgers", "Serve %# burgers."),
            new String[] {
                "-",
                "Serveer %# burgers.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-practice", "Play %# levels to unlock the practice area."),
            new String[] {
                "-",
                "Win %# levels om het oefenterrein te ontgrendelen.",
            }
        );
    }

    @Override
    public int plural(int n) {
        return (n != 1) ? 1 : 0;
    }
}