// This file has been dynamically generated by po-compile.
// Do not modify it, all changes will be lost.

public class Messages_ru extends com.greenyetilab.linguaj.Messages {
    public Messages_ru() {
        plainEntries.put("%dx combo!", "%dx кобмо!");
        plainEntries.put("About", "Об игре");
        plainEntries.put("All Stars #%d", "Все звёздочки #%d");
        plainEntries.put("Burger Apprentice", "Бургерный ученик");
        plainEntries.put("Burger God", "Бургерный король");
        plainEntries.put("Burger Master", "Бургерный мастер");
        plainEntries.put("Buy Burger Party goodies!", "Купить футболки\nБургерной Вечеринки");
        plainEntries.put("Close Call", "На грани краха");
        plainEntries.put("Code & Design", "Код и дизайн");
        plainEntries.put("Congratulations, you finished level %d-%d!", "Поздравляем, вы прошли уровень %d-%d!");
        plainEntries.put("Congratulations, you finished the game!", "Поздравляем, вы прошли эту игру!");
        plainEntries.put("Congratulations, you finished world %d!", "Поздравляем, вы прошли мир %d!");
        plainEntries.put("Creative", "Изобретательно");
        plainEntries.put("Evening Gamer", "Вечерний игрок");
        plainEntries.put("Fan", "Фан");
        plainEntries.put("Finish all levels of world %d with 3 stars.", "Пройдите все уровни мира %d с трёмя звёздами");
        plainEntries.put("Follow me on Mastodon", "Подписаться на Mastodon");
        plainEntries.put("Fonts", "Шрифты");
        plainEntries.put("Game Over", "Конец игры");
        plainEntries.put("Get a perfect in all levels of world %d.", "Станьте отличным на всех уровнях мира %d.");
        plainEntries.put("Goodies", "Футболки");
        plainEntries.put("Happy customer!", "Довольный клиент!");
        plainEntries.put("High score: %d", "Наилучшие баллы: %d");
        plainEntries.put("Level %d-%d", "Уровень %d-%d");
        plainEntries.put("Like the game? Give it a good rate!", "Понравилась игра? Дайте ей хорошую оценку!");
        plainEntries.put("Like the game? Support my work!", "Нравиться игра? Поддержите мою работу!");
        plainEntries.put("Mastodon", "Mastodon");
        plainEntries.put("Morning Gamer", "Утренний игрок");
        plainEntries.put("Music", "Музыка");
        plainEntries.put("New High Score!", "Новый наилучший балл!");
        plainEntries.put("New item unlocked!", "Открыт новый предмет");
        plainEntries.put("No high score yet", "Ещё нет баллов");
        plainEntries.put("Paused", "Приостановлено");
        plainEntries.put("Perfect #%d", "Отлично #%d");
        plainEntries.put("Practice Area", "Учебная");
        plainEntries.put("Rate Burger Party", "Оцените Бургерную вечеринку");
        plainEntries.put("Sound", "Звук");
        plainEntries.put("Sound is OFF", "Звук ВЫКЛ");
        plainEntries.put("Sound is ON", "Звук ВКЛ");
        plainEntries.put("Sounds", "Звуки");
        plainEntries.put("Star Collector", "Собиратель звёздочек");
        plainEntries.put("Support Burger Party", "Поддержать Бургерную вечеринку");
        plainEntries.put("Testers", "Тестировщики");
        plainEntries.put("Thank you for playing!", "Спасибо что играете!");
        plainEntries.put("Thomas Tripon", "Томас Трипон");
        plainEntries.put("Version %s", "Версия %s");
        plainEntries.put("Who made this?", "Кто её сделал?");
        pluralEntries.put(
            new PluralId("+%# sec", "+%# sec"),
            new String[] {
                "+%# секунда",
                "+%# секунды",
                "+%# секунд",
            }
        );
        pluralEntries.put(
            new PluralId("1 remaining.", "%# remaining."),
            new String[] {
                "Остался %#.",
                "Остались %#.",
                "Осталось %#.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-close-call", "Finish a level with less than %# seconds left."),
            new String[] {
                "Завершите уровень, когда до конца осталось менее %# секунды.",
                "Завершите уровень, когда до конца осталось менее %# секунды.",
                "Завершите уровень, когда до конца осталось менее %# секунд.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-collect", "Collect %# stars."),
            new String[] {
                "Собрать %# звезду.",
                "Собрать %# звёзд.",
                "Собрать %# звезды.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-creative", "Create %# different burgers in the practice area."),
            new String[] {
                "Сделайте %# бургер на тренировочном уровне.",
                "Сделайте %# бургера на тренировочном уровне.",
                "Сделайте %# бургеров на тренировочном уровне.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-evening", "Start a game between 7PM and 11PM for %# days."),
            new String[] {
                "Запустите игру один раз между 19:00 и 23:00 %# день.",
                "Запустите игру один раз между 19:00 и 23:00 %# дня.",
                "Запустите игру один раз между 19:00 и 23:00 %# дней.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-fan", "Play %# levels."),
            new String[] {
                "Играть %# уровень.",
                "Играть %# уровня.",
                "Играть %# уровней.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-morning", "Start a game between 7AM and 10AM for %# days."),
            new String[] {
                "Начните игру между 7:00 и 10:00 в течение %# дня.",
                "Начните игру между 7:00 и 10:00 в течение %# дней.",
                "Начните игру между 7:00 и 10:00 в течение %# дней.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-n-burgers", "Serve %# burgers."),
            new String[] {
                "Подал %# бургер.",
                "Подал %# бургера.",
                "Подал %# бургеров.",
            }
        );
        pluralEntries.put(
            new PluralId("ignore-practice", "Play %# levels to unlock the practice area."),
            new String[] {
                "Играйте %# уровень чтобы открыть учебную комнату.",
                "Играйте %# уровня чтобы открыть учебную комнату.",
                "Играйте %# уровней чтобы открыть учебную комнату.",
            }
        );
    }

    @Override
    public int plural(int n) {
        return n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;
    }
}