// This file has been dynamically generated by po-compile.
// Do not modify it, all changes will be lost.

public class Messages_eu extends com.greenyetilab.linguaj.Messages {
    public Messages_eu() {
        plainEntries.put("%dx combo!", "%dx konboa!");
        plainEntries.put("About", "Honi buruz");
        plainEntries.put("All Stars #%d", "#%d izar guztiak");
        plainEntries.put("Burger Apprentice", "Burger Ikaslea");
        plainEntries.put("Burger God", "Burger Jainkoa");
        plainEntries.put("Burger Master", "Burger Nagusia");
        plainEntries.put("Buy Burger Party goodies!", "Erosi Burger Party-ko\ngutiziak!");
        plainEntries.put("Close Call", "Azken Deia");
        plainEntries.put("Code & Design", "Kodea & Diseinua");
        plainEntries.put("Congratulations, you finished level %d-%d!",
                "Zorionak, %d-%d maila bukatu duzu!");
        plainEntries.put("Congratulations, you finished the game!", "Zorionak, jokoa bukatu duzu!");
        plainEntries.put("Congratulations, you finished world %d!", "Zorionak, %d mundua bukatu duzu!");
        plainEntries.put("Creative", "Sortzailea");
        plainEntries.put("Evening Gamer", "Arratsaldeko jokalaria");
        plainEntries.put("Fan", "Fan");
        plainEntries.put("Finish all levels of world %d with 3 stars.",
                "Bukatu %d munduko maila guztiak 3 izarrekin.");
        plainEntries.put("Follow me on Mastodon", "Jarrai nazazu Mastodon-en");
        plainEntries.put("Fonts", "Letra-tipoak");
        plainEntries.put("Game Over", "Akabo Jokoa");
        plainEntries.put("Get a perfect in all levels of world %d.",
                "Egizu bikain %d munduko maila guztietan.");
        plainEntries.put("Goodies", "Gutiziak");
        plainEntries.put("Happy customer!", "Bezeroa pozik!");
        plainEntries.put("High score: %d", "Marka: %d");
        plainEntries.put("Level %d-%d", "%d-%d maila");
        plainEntries.put("Like the game? Give it a good rate!", "Jokoa gustuko duzu? Puntua ezazu altu!");
        plainEntries.put("Like the game? Support my work!", "Jokoa gustuko duzu? Babestu nire lana!");
        plainEntries.put("Mastodon", "Mastodon");
        plainEntries.put("Morning Gamer", "Goizeko Jokalaria");
        plainEntries.put("Music", "Musika");
        plainEntries.put("New High Score!", "Marka berria!");
        plainEntries.put("New item unlocked!", "Item berria lortu duzu!");
        plainEntries.put("No high score yet", "Oraindik markarik ez");
        plainEntries.put("Paused", "Pausatuta");
        plainEntries.put("Perfect #%d", "#%d Bikain");
        plainEntries.put("Practice Area", "Praktika Txokoa");
        plainEntries.put("Rate Burger Party", "Puntuatu Burger Party");
        plainEntries.put("Sound", "Soinua");
        plainEntries.put("Sound is OFF", "Soinua OFF");
        plainEntries.put("Sound is ON", "Soinua ON");
        plainEntries.put("Sounds", "Soinuak");
        plainEntries.put("Star Collector", "Izar Biltzailea");
        plainEntries.put("Support Burger Party", "Babestu Burger Party");
        plainEntries.put("Testers", "Tester-ak");
        plainEntries.put("Thank you for playing!", "Eskerrik asko jostatzeagatik!");
        plainEntries.put("Thomas Tripon", "Thomas Tripon");
        plainEntries.put("Version %s", "%s tertsioa");
        plainEntries.put("Who made this?", "Nork egin du hau?");
        pluralEntries.put(
                new PluralId("+%# sec", "+%# sec"),
                new String[] {
                        "+%# segundo",
                        "+%# segundo",
                });
        pluralEntries.put(
                new PluralId("1 remaining.", "%# remaining."),
                new String[] {
                        "1 faltan.",
                        "%# faltan.",
                });
        pluralEntries.put(
                new PluralId("ignore-close-call", "Finish a level with less than %# seconds left."),
                new String[] {
                        "-",
                        "Buka ezazu maila bat %# baino segundo gutxiago falta direlarik.",
                });
        pluralEntries.put(
                new PluralId("ignore-collect", "Collect %# stars."),
                new String[] {
                        "-",
                        "Lortu %# izar.",
                });
        pluralEntries.put(
                new PluralId("ignore-creative", "Create %# different burgers in the practice area."),
                new String[] {
                        "-",
                        "Sortu %# burger desberdin praktika txokoan.",
                });
        pluralEntries.put(
                new PluralId("ignore-evening", "Start a game between 7PM and 11PM for %# days."),
                new String[] {
                        "-",
                        "Hasi jokoan 19:00ak eta 23:00ak bitartean %# egunez.",
                });
        pluralEntries.put(
                new PluralId("ignore-fan", "Play %# levels."),
                new String[] {
                        "-",
                        "Jostatu %# mailatan.",
                });
        pluralEntries.put(
                new PluralId("ignore-morning", "Start a game between 7AM and 10AM for %# days."),
                new String[] {
                        "-",
                        "Hasi jokoan 7:00ak eta 10:00ak bitartean %# egunez.",
                });
        pluralEntries.put(
                new PluralId("ignore-n-burgers", "Serve %# burgers."),
                new String[] {
                        "-",
                        "Zerbitzatu %# burger.",
                });
        pluralEntries.put(
                new PluralId("ignore-practice", "Play %# levels to unlock the practice area."),
                new String[] {
                        "-",
                        "Jokatu %# maila praktika txokoa irekitzeko.",
                });
    }

    @Override
    public int plural(int n) {
        return (n > 1) ? 1 : 0;
    }
}