/* This file has been generated by gensignals.py. Do not edit */
package com.agateau.burgerparty.utils;

import java.lang.ref.WeakReference;

public class Signal3<T1, T2, T3> extends AbstractSignal<Signal3.Handler<T1, T2, T3>> {
	public interface Handler<T1, T2, T3> extends Signal.Handler {
		void handle(T1 a1, T2 a2, T3 a3);
	}

	public void emit(T1 a1, T2 a2, T3 a3) {
		for(WeakReference<Handler<T1, T2, T3>> ref : mHandlers) {
			Handler<T1, T2, T3> handler = ref.get();
			if (handler != null) {
				handler.handle(a1, a2, a3);
			}
		}
	}
}
