/* This file has been generated by gensignals.py. Do not edit */
package com.agateau.burgerparty.utils;

public class Signal2<T1, T2> extends AbstractSignal<Signal2.Handler<T1, T2>> {
	public interface Handler<T1, T2> {
		void handle(T1 a1, T2 a2);
	}

	public void emit(T1 a1, T2 a2) {
		for(Handler<T1, T2> handler : mHandlers) {
			handler.handle(a1, a2);
		}
	}
}
