/* This file has been generated by gensignals.py. Do not edit */
package com.agateau.burgerparty.utils;

import java.lang.ref.WeakReference;

public class Signal2<T1, T2> extends AbstractSignal<Signal2.Handler<T1, T2>> {
	public interface Handler<T1, T2> extends Signal.Handler {
		void handle(T1 a1, T2 a2);
	}

	public void emit(T1 a1, T2 a2) {
		for(WeakReference<Handler<T1, T2>> ref : mHandlers) {
			Handler<T1, T2> handler = ref.get();
			if (handler != null) {
				handler.handle(a1, a2);
			}
		}
	}
}
