/* This file has been generated by gensignals.py. Do not edit */
package com.agateau.burgerparty.utils;

public class Signal0 extends AbstractSignal<Signal0.Handler> {
	public interface Handler extends Signal.Handler {
		void handle();
	}

	public void emit() {
		for(Handler handler : mHandlers) {
			handler.handle();
		}
	}
}
