/* This file has been generated by gensignals.py. Do not edit */
package com.agateau.burgerparty.utils;

import java.lang.ref.WeakReference;

public class Signal4<T1, T2, T3, T4> extends AbstractSignal<Signal4.Handler<T1, T2, T3, T4>> {
    public interface Handler<T1, T2, T3, T4> extends Signal.Handler {
        void handle(T1 a1, T2 a2, T3 a3, T4 a4);
    }

    public void emit(T1 a1, T2 a2, T3 a3, T4 a4) {
        for (WeakReference<Handler<T1, T2, T3, T4>> ref : mHandlers) {
            Handler<T1, T2, T3, T4> handler = ref.get();
            if (handler != null) {
                handler.handle(a1, a2, a3, a4);
            }
        }
    }
}
