#!/bin/sh
set -e
cd $(dirname $0)/..
BP_DIR=$PWD

CLASSPATH="$BP_DIR/burgerparty/bin:$BP_DIR/burgerparty-desktop/bin"
for jar in $BP_DIR/burgerparty/libs/*.jar $BP_DIR/burgerparty-desktop/libs/*.jar ; do
    CLASSPATH="$CLASSPATH:$jar"
done

cd burgerparty-desktop
java -cp $CLASSPATH com.agateau.burgerparty.Main
