#!/bin/sh
set -e
GDXDIR=/home/aurelien/opt/libgdx-0.9.9
#GDXDIR=/home/aurelien/opt/libgdx-20130630
cd $(dirname $0)/..
BPDIR=$PWD/burgerparty/bin
BPDESKTOPDIR=$PWD/burgerparty-desktop/bin

CLASSPATH="$BPDIR:$BPDESKTOPDIR"
JARS="
gdx
gdx-natives
gdx-backend-lwjgl
gdx-backend-lwjgl-natives
extensions/gdx-tools/gdx-tools
"
for jar in $JARS ; do
    CLASSPATH="$CLASSPATH:$GDXDIR/$jar.jar"
done
echo $CLASSPATH

java -cp $CLASSPATH com.agateau.burgerparty.Main
