#!/bin/sh
set -e
cd $(dirname $0)/..

XML_FILE=$PWD/android/assets/mealitems.xml

show=0
if [ "$1" = "show" ] ; then
    show=1
fi

xmlstarlet select --text --template --match "/items/generic/item" \
    -v @world -o "." -v @level -o " " -v @name --nl \
    $XML_FILE \
    | sed 's/^\./1.1/' \
    | sort --version-sort \
    > out

if [ "$show" = "1" ] ; then
    cat out
    rm out
    exit 0
fi

vi out
cp $XML_FILE $XML_FILE.old
cat out | sed 's/\./ /' | while read world level item ; do
    item_xpath="/items/generic/item[@name='$item']"
    xmlstarlet edit --inplace \
        --delete $item_xpath/@world \
        --delete $item_xpath/@level \
        $XML_FILE > /dev/null 2>&1 || true

    if [ $world -ne 1 -o $level -ne 1 ] ; then
        xmlstarlet edit --inplace \
        --append $item_xpath --type attr -n world -v $world \
        --append $item_xpath --type attr -n level -v $level \
        $XML_FILE
    fi
done
rm $XML_FILE.old
rm out
