#!/bin/sh
set -e
cd $(dirname $0)/..
BP_DIR=$PWD

CLASSPATH="bin:"
for jar in $BP_DIR/burgerparty/libs/*.jar $BP_DIR/burgerparty-desktop/libs/*.jar ; do
    CLASSPATH="$CLASSPATH:$jar"
done

cd burgerparty-desktop
notify-send Packer "Start packing"
java -cp $CLASSPATH com.agateau.burgerparty.PackerMain
notify-send Packer "Done"
