#!/bin/sh
set -e
cd $(dirname $0)/..
BP_DIR=$PWD

CLASSPATH=""
for jar in $BP_DIR/burgerparty/build/libs/*.jar $BP_DIR/burgerparty-desktop/build/libs/*.jar ; do
    CLASSPATH="$CLASSPATH:$jar"
done

TESTS=$(cd burgerparty/src && find -name '*Test.java' | sed -e 's|^\./||' -e 's|\.java$||' -e 's|/|.|g')
java -cp $CLASSPATH org.junit.runner.JUnitCore $TESTS
