#!/bin/sh
set -e
cd $(dirname $0)/..
BP_DIR=$PWD
ASSETS_DIR=$BP_DIR/burgerparty-android/assets

BUILD_DIR=$BP_DIR/out/production

CLASSPATH="$BUILD_DIR/burgerparty:$BUILD_DIR/burgerparty-desktop:$BUILD_DIR/linguaj"
for jar in $BP_DIR/burgerparty/libs/*.jar $BP_DIR/burgerparty-desktop/libs/*.jar ; do
    CLASSPATH="$CLASSPATH:$jar"
done

cd burgerparty-desktop
notify-send Packer "Start packing"
java -cp $CLASSPATH com.agateau.burgerparty.PackerMain

sleep 1
touch $ASSETS_DIR/*.png $ASSETS_DIR/burgerparty.atlas

notify-send Packer "Done"
